version: "3.8"
services:

    agile:
        container_name: agile
        hostname: agile
        labels:
            description: Agile Data Science 2.0
            name: agile
        tty: true
        image: jupyter/pyspark-notebook:spark-3.2.0
        build:
            context: .
            dockerfile: Dockerfile
            args:
                buildno: 1
        user: root
        environment:
            JUPYTER_ENABLE_LAB: "yes"
            GRANT_SUDO: "yes"
        depends_on:
            - elastic
            - mongo
            - mongo-express
        ports:
            - "8888:8888"
        volumes:
            - ./:/home/jovyan
            - agile_data:/home/jovyan/data
        networks:
            - agile_net

    elastic:
        container_name: elastic
        hostname: elastic
        labels:
            description: Agile Data Science 2.0 Elastic
            name: elastic
        tty: True
        image: elasticsearch:7.14.2
        environment:
            discovery.type: single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - elastic_data:/usr/share/elasticsearch/data
        networks:
            - agile_net

    mongo:
        container_name: mongo
        hostname: mongo
        labels:
            description: Agile Data Science 2.0 MongoDB
            name: mongo
        image: mongo:5.0.3
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: agile
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - agile_net

    mongo-express:
        container_name: mongo-express
        hostname: mongo-express
        labels:
            description: Agile Data Science 2.0 Mongo Express
            name: mongo-express
        image: mongo-express:0.54.0
        depends_on:
            - mongo
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: agile
            ME_CONFIG_MONGODB_URL: mongodb://root:agile@mongo:27017/
        networks:
            - agile_net

    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    scheduler:
        container_name: scheduler
        hostname: scheduler
        labels:
            description: Agile Data Science 2.0 Airflow 1.10.15 Scheduler
            name: scheduler
        image: apache/airflow:1.10.15
        command: scheduler
        restart: on-failure
        depends_on:
            - postgres
        env_file:
            - airflow.env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs

    webserver:
        container_name: webserver
        hostname: webserver
        labels:
            description: Agile Data Science 2.0 Airflow 1.10.15 Webserver
            name: webserver
        image: apache/airflow:1.10.15
        command: webserver
        restart: on-failure
        depends_on:
            - postgres
            - scheduler
        env_file:
            - airflow.env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"

volumes:
    agile_data:
    elastic_data:
    mongo_data:

networks:
    agile_net:
        name: agile_net
        driver: bridge